# Generated by Django 6.0.1 on 2026-01-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('cough', models.BooleanField()),
                ('rasp', models.BooleanField()),
                ('temperature', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('leukocytes', models.FloatField()),
                ('neutrophils', models.FloatField()),
            ],
        ),
    ]
