# Generated by Django 6.0.1 on 2026-04-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clinicaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinicalData',
        ),
    ]
