# Generated by Django 6.0.1 on 2026-02-01 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(verbose_name='Вік')),
                ('cough', models.BooleanField(default=False, verbose_name='Кашель')),
                ('rasp', models.BooleanField(default=False, verbose_name='Хрипи')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('hemoglobin', models.FloatField(verbose_name='Гемоглобін')),
                ('leukocytes', models.FloatField(verbose_name='Лейкоцити')),
                ('neutrophils', models.FloatField(verbose_name='Нейтрофіли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата аналізу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пацієнт')),
            ],
        ),
        migrations.CreateModel(
            name='XRayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m', verbose_name='Рентген')),
                ('result', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата аналізу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
