# Generated by Django 6.0.1 on 2026-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='altered_mental_status',
            field=models.BooleanField(default=False, verbose_name='Сплутаність свідомості'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='cancer',
            field=models.BooleanField(default=False, verbose_name='Онкологічні захворювання'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='cerebrovascular_disease',
            field=models.BooleanField(default=False, verbose_name='Цереброваскулярні хвороби (інсульт)'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловік'), ('F', 'Жінка')], default='M', max_length=1, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='heart_disease',
            field=models.BooleanField(default=False, verbose_name='Серцева недостатність'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='liver_disease',
            field=models.BooleanField(default=False, verbose_name='Захворювання печінки'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='nursing_home',
            field=models.BooleanField(default=False, verbose_name='Проживання в будинку престарілих'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='pulse',
            field=models.PositiveIntegerField(default=70, verbose_name='Пульс (уд/хв)'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='renal_disease',
            field=models.BooleanField(default=False, verbose_name='Захворювання нирок'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='respiratory_rate',
            field=models.PositiveIntegerField(default=18, verbose_name='Частота дихання (вдихів/хв)'),
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='systolic_bp',
            field=models.PositiveIntegerField(default=120, verbose_name='Систолічний тиск (верхній)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='hemoglobin',
            field=models.FloatField(verbose_name='Гемоглобін (г/л)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='temperature',
            field=models.FloatField(verbose_name='Температура (°C)'),
        ),
    ]
