# Generated by Django 6.0.1 on 2026-02-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_clinicaldata_mortality_prediction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicaldata',
            name='leukocytes',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='neutrophils',
        ),
    ]
