# Generated by Django 6.0.1 on 2026-02-04 10:24

import diagnosis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_remove_clinicaldata_leukocytes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xraydata',
            name='image',
            field=models.ImageField(upload_to=diagnosis.utils.user_directory_path, verbose_name='Рентген'),
        ),
    ]
