# Generated by Django 6.0.1 on 2026-04-01 10:01

import diagnosis.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_alter_xraydata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='hemoglobin',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(250.0)], verbose_name='Гемоглобін (г/л)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='pulse',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Пульс (уд/хв)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='respiratory_rate',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)], verbose_name='Частота дихання (вдихів/хв)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='systolic_bp',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)], verbose_name='Систолічний тиск (верхній)'),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='xraydata',
            name='image',
            field=models.ImageField(upload_to=diagnosis.utils.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Рентген'),
        ),
    ]
